import { StyleSheet, Dimensions } from 'react-native';
import { Color, Font } from '../../../../constants';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.White,
  },
  pagerView: {
    flex: 1,
  },
  fullScreenPage: {
    flex: 1,
    width: SCREEN_WIDTH,
    backgroundColor: Color.White,
  },
  statusHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  statusHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusHeaderTitle: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 16,
    color: Color.TextPrimary,
  },
  statusHeaderBadge: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  statusHeaderBadgeText: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 14,
    color: Color.White,
  },
  pageScrollView: {
    flex: 1,
  },
  pageScrollContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 32,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 14,
    color: '#999',
    fontFamily: Font.InterRegular400,
  },
  taskCard: {
    borderRadius: 10,
    backgroundColor: Color.White,
    padding: 12,
    borderWidth: 1,
    borderColor: '#EAECF0',
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  taskCardSpacing: {
    marginBottom: 12,
  },
  taskCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  taskCardTitle: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 14,
    color: Color.TextPrimary,
    flex: 1,
    marginRight: 8,
  },
  taskCardMenuButton: {
    padding: 4,
  },
  taskCardDescription: {
    fontSize: 12,
    color: '#667085',
    marginTop: 6,
    fontFamily: Font.InterRegular400,
  },
  taskPriorityChip: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
  },
  taskPriorityChipText: {
    fontSize: 11,
    fontFamily: Font.InterMedium500,
  },
  taskCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  taskCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
  },
  taskCardMetaIcon: {
    width: 16,
    height: 16,
  },
  taskCardMetaText: {
    fontSize: 12,
    color: '#475467',
    fontFamily: Font.InterRegular400,
  },
  taskCardContainer: {
    backgroundColor: Color.White,
    borderRadius: 8,
    marginBottom: 12,
    overflow: 'hidden',
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  taskStatusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  taskStatusBarText: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 14,
    color: Color.White,
    textTransform: 'uppercase',
  },
  taskStatusBarBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Color.White,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskStatusBarBadgeText: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 12,
    color: Color.TextPrimary,
  },
  taskCardContent: {
    padding: 16,
    rowGap: 10,
  },
  taskNameRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    columnGap: 10,
  },
  taskName: {
    flex: 1,
    fontSize: 14,
    fontFamily: Font.InterMedium500,
    color: Color.TextPrimary,
    lineHeight: 20,
  },
  assignedIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 4,
  },
  assignedIndicatorText: {
    fontSize: 11,
    fontFamily: Font.InterMedium500,
    color: '#22C55E',
  },
  taskDateText: {
    fontSize: 12,
    fontFamily: Font.InterRegular400,
    color: '#00204DE5',
  },
  taskProgressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  taskProgressBar: {
    width: 100,
    height: 8,
    borderRadius: 4,
  },
  taskProgressText: {
    fontSize: 12,
    fontFamily: Font.InterRegular400,
    color: Color.TextPrimary,
  },
  taskTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 6,
    rowGap: 6,
  },
  taskTag: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00358026',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    columnGap: 6,
  },
  taskTagText: {
    fontSize: 12,
    fontFamily: Font.InterBold700,
    color: Color.TextPrimary,
    maxWidth: 80,
  },
  taskTagBadge: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Color.TextPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskTagBadgeText: {
    fontSize: 8,
    fontFamily: Font.InterBold700,
    color: Color.White,
  },
  taskMetadataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    marginTop: 4,
  },
  taskUserAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Color.White,
  },
  taskUserAvatarMore: {
    backgroundColor: '#F2F4F7',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#F2F4F7',
  },
  taskUserAvatarMoreText: {
    fontSize: 10,
    fontFamily: Font.InterBold700,
    color: '#606C80',
  },
  taskAddUserButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Color.Text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskMetadataItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 3,
  },
  taskMetadataText: {
    fontSize: 10,
    fontFamily: Font.InterBold700,
  },
  addTaskContainer: {
    backgroundColor: Color.White,
    borderRadius: 8,
    marginTop: 10,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addTaskButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 8,
  },
  addTaskIcon: {
    width: 20,
    height: 20,
  },
  addTaskText: {
    fontSize: 14,
    fontFamily: Font.InterRegular400,
    color: '#00204D',
  },
  detailCard: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: Color.White,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EAECF0',
    shadowColor: '#101828',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  detailCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailCardTitle: {
    flex: 1,
    marginRight: 12,
    fontFamily: Font.InterSemiBold600,
    fontSize: 16,
    color: Color.TextPrimary,
  },
  statusChip: {
    backgroundColor: '#E0E7FF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  statusChipText: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 12,
    color: '#4338CA',
  },
  detailCardDescription: {
    fontSize: 13,
    color: '#475467',
    marginBottom: 8,
  },
  detailCardPlaceholder: {
    fontSize: 13,
    color: '#98A2B3',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  detailCardMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  detailCardMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  detailCardMetaText: {
    fontSize: 12,
    color: '#475467',
  },
  metaIcon: {
    width: 18,
    height: 18,
  },
  tabContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  loadingContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boardColumns: {
    flexDirection: 'row',
    columnGap: 16,
    paddingBottom: 32,
  },
  boardColumn: {
    width: 260,
    borderRadius: 12,
    padding: 12,
  },
  boardColumnHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  boardColumnTitle: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 14,
    color: Color.TextPrimary,
  },
  boardColumnBadge: {
    minWidth: 28,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  boardColumnBadgeText: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 12,
    color: Color.White,
  },
  boardColumnBody: {
    flexDirection: 'column',
  },
  boardEmptyState: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  boardEmptyText: {
    fontSize: 13,
    color: '#999',
  },
  boardCard: {
    borderRadius: 10,
    backgroundColor: Color.White,
    padding: 12,
    borderWidth: 1,
    borderColor: '#EAECF0',
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  boardCardSpacing: {
    marginBottom: 12,
  },
  boardCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  boardCardTitle: {
    fontFamily: Font.InterSemiBold600,
    fontSize: 14,
    color: Color.TextPrimary,
    flex: 1,
    marginRight: 8,
  },
  boardCardMenuButton: {
    padding: 4,
  },
  boardCardMetaIcon: {
    width: 16,
    height: 16,
  },
  boardCardDescription: {
    fontSize: 12,
    color: '#667085',
    marginTop: 6,
  },
  boardPriorityChip: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
  },
  boardPriorityChipText: {
    fontSize: 11,
    fontFamily: Font.InterMedium500,
  },
  boardCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  boardCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
  },
  boardCardMetaText: {
    fontSize: 12,
    color: '#475467',
  },
});


